---
# Source: kubernetes-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-appdb
  namespace: mongodb
---
# Source: kubernetes-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-database-pods
  namespace: mongodb
---
# Source: kubernetes-operator/templates/database-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-ops-manager
  namespace: mongodb
---
# Source: kubernetes-operator/templates/database-roles.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-appdb
  namespace: mongodb
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get
---
# Source: kubernetes-operator/templates/database-roles.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-appdb
  namespace: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-kubernetes-appdb
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-appdb
    namespace: mongodb
