blank_issues_enabled: false
contact_links:
    - name: MongoDB Feedback
      url: https://feedback.mongodb.com/?category=7548142104564903515
      about: Use our Feedback page for making feature requests.
